config/routes.rb
Rails.application.routes.draw do

  # Set Project Home Page #
  root 'static_pages#home'

  # Set Project STatic Pages #
  get '/help',  to: 'static_pages#help'
  get '/about',  to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # Set Users Paths #
  get '/signup',  to: 'users#new'
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"


  # Set Project Resources #
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :username, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 20 }
  validates :access_code, presence: true, length: { maximum: 3 }, allow_nil: true
  validates :agency_name, presence: true, length: { maximum: 30 }, allow_nil: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # Returns a session token to prevent session hijacking.
  # We reuse the remember digest for convenience.
  def session_token
    remember_digest || remember
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url, status: :see_other
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to EZ-Rater Pro!"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url, status: :see_other
  end

  private

    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :agency_name, :access_code, :email, :password, :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url, status: :see_other
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url, status: :see_other) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url, status: :see_other) unless current_user.admin?
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "EZ-Rater Pro"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
    # Guard against session replay attacks.
    # See https://bit.ly/33UvK0w for more.
    session[:session_token] = user.session_token
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user && user == current_user
  end


  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    reset_session
    @current_user = nil
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag('tsu.png', width: '300', height: '75'), root_path, id: 'logo' %>
    <nav>
      <div class="navbar-header">
        <button id="hamburger" type="button" class="navbar-toggle collapsed">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul id="navbar-menu" class="nav navbar-nav navbar-right collapse navbar-collapse">
        <li><%= link_to "Home", root_path, id: 'ez_menu' %></li>
        <li><%= link_to "Help", help_path, id: 'ez_menu' %></li>
        <li><%= link_to "About", about_path, id: 'ez_menu' %></li>
        <li><%= link_to "Contact", contact_path, id: 'ez_menu' %></li>
        <% if logged_in? %>
          <li><% if current_user.admin? %><%= link_to "Agents", users_path, id: 'ez_menu' %><% end %></li>
          <li class="dropdown" id="ez_menu">
            <a href="#" id="account" class="dropdown-toggle" style="color: #FFF">
              Account <b class="caret"></b>
            </a>
            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, data: { "turbo-method": :delete } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path, id: 'ez_menu' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header><br/>
<br/>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= render 'layouts/shim' %>
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">    
    <!-- Add Google Fonts; -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=IBM+Plex+Mono&family=Luckiest+Guy&family=Orbitron&family=Righteous&display=swap" rel="stylesheet">
    <!-- Add Google Tracking; -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-K5JNQX8XBT"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-K5JNQX8XBT');
    </script>
    <%= javascript_importmap_tags %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron aboutDiv">
  <h1 class="about_header">
    About EZ-Rater Pro
  </h1><br/>
  <br/>
  <p class="about_paragraph">
    <i>This software is property of B1-Technologies. </i><br/>
    <br/>
    This is an online EZ-Rating software that will allow insruance agencies to easily pull quotes from
    multiple insurance agencies and select the best priced quote. <br/>
    <br/>
    <strong>How Does This Work?</strong><br/>
    Easy! The first thing you must do is register for an account. Once your account is setup and you have
    access, you simply click on "New Contract" and fill out the application for your new client.
    Once you filled out all of the important data, then you will be able to see a list of quotes from various
    insurance companies. Select the one you desire most, and it will take you to their website to finish
    binding the contract. Once that is completed, then you can see a list of quotes you have generated in
    your dashboard so you can easily go back and retrieve the information from a previous quote.<br/>
    <br/>
    <strong>How Do I Register?</strong><br/>
    To register for an account, you will need the following information;<br/>
    <i>* Insurance Agency Name</i><br/>
    <i>* Insurance Agency Code</i><br/>
    <i>* Email Address</i><br/>
    <i>* Username</i><br/>
    <i>* Password</i><br/>
    <i>* First Name</i><br/>
    <i>* Last Name</i><br/>
    <u><b>Please Note:</b> The "Insurance Agency Code" is provided by EZ-Rator Pro upon their successfull subscription of our services.</u><br/>
    <br/>
    <strong>How Long Is The Trail Period?</strong><br/>
    EZ-Rater Pro give every Insurance Agency &amp; Underwriting Agency a gracious 30-Day test run. After that, you will be charged accordingly.
    We give such a generious trial period as we want each agency to be able to fully test out the software to their needs &amp; desires before
    making such a massive commitment to our software. <br/>
    During your trial period, we also highly encourage users to give feed back on the platform and provide any suggestions they may have
    to help improve our system for not just them, but for others as well!<br/>
    <br/>
    <strong>How Much Does This Cost?</strong><br/>
    Here at EZ-Rater Pro, powered by <i><b>B1-Technologies</b></i>, has the lowest overhead costs possible
    for this type of organization. While we write the code, host the applications, and delivery outstanding
    services for everyone to enjoy, we have an extremely low overhead cost. This means our savings is passed
    on to you. So what will this cost you? An amazing <strong>$1,500 Per Month</strong> to obtain unlimited quotes from our system!<br/>
    <br/>
    <strong>What Technologies Do We Use?</strong><br/>
    Our talented and amazing developer has setup everything to run smoothly and efficeintly to provide your firm with the easist
    and fastest response time possible! How does he make all of this possible?<br/>
    <i>He utilizes the following methods;</i><br/>
    <b>Ruby on Rails Framework</b><br/>
    <b>Cloud Hosting Services</b><br/>
    <b>Custom Built Firewall Rules</b><br/>
    <b>24/7-365 Monitoring</b><br/>
    <b>SSH Keys ~ TO allow ONLY him to get access to the servers!</b><br/>
    <b>Latest SQL Databases</b><br/>
    Discover how fast and amazing EZ-Rater Pro can be for your company and start saving money today!<br/>
  </p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center jumbotron aboutDiv">
  <h1 class="about_header">
    Contact EZ-Rater Pro
  </h1><br/>
  <br/>
  <p class="about_paragraph">
    If you would like to contact EZ-Rater Pro, we would love to hear from you! Please use any of the following methods
    to contact us in regards of your issues with our software;<br/>
    For inquiries about using the software, questions about pricing &amp; contracts, and general information, please email us at;<br/>
    info@ezraterpro.com<br/>
    Or call us at;<br/>
    +1 (817) 555-0505<br/>
    For inquires about new services for the software, issues with login, and other general tech questions or issues, please email us at;<br/>
    tech@ezraterpro.com<br/>
    Or call us at;<br/>
    +1 (817) 555-0506<br/>
  </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="center jumbotron helpDiv">
  <h1 class="about_header">
    Help With EZ-Rater Pro
  </h1><br/>
  <br/>
  <p class="about_paragraph">
    This page will allow you to discover how you can work through this web application and
    get your firm registered in no time at all!<br/>
    <br/>
    <strong>How To Register My Firm?</strong><br/>
    In order to register your firm, you can easily send us an email, or give us a call. Once
    we have successfully setup your firm in our database, you are given a special "Access Code"
    that you can give your associates in order to allow them to register for an account.<br/>
    <br/>
    <strong>How To Register A New Account?</strong><br/>
    When your firm registers with EZ-Rater Pro, they are given a special Access Code that you will
    need in order to finish your registration with this website. Once you have the Access Code, you
    will then need to fill out the "Registration" form and will require the following;<br/>
    Email<br/>
    Password<br/>
    Username<br/>
    Access Code<br/>
    First Name<br/>
    Last Name<br/>
    Once you have those setup, then you will be redirected to your new account and can start pulling quotes
    as soon as you get in!<br/>
    <br/>
    <strong>How To Get Quotes?</strong><br/>
    Our easy-to-follow insurance quote form allows you to input the desired variables for your clients needs.
    After you have inserted all of the standard information in our form, we will parse our form through various
    API Keys in order to generate multiple quotes for your client. Once you have the quotes back, you simply
    select the desired insurance company and you will be able to generate a DOC file that you can download and
    you will be able to go to the respective insurance website to finish binding your contract!<br/>
    <br/>
    <strong>What Happens If We Don't Pay?</strong><br/>
    Failure to pay will result in loss of access to your firm, and your associates. Which will disrupt their
    work time and will have to do things another way. But do not fear, we do not delete any of your data for
    no-pay accounts. You will be able to recover your access again upon successful payment to keep using our
    software. <br/>
    <br/>
    <strong>Do I need to sign a contract?</strong><br/>
    While we do have contracts in place you can sign up for, we can also handle month-to-month basis. Much
    like a prepaid phone line, you only pay for the month ahead of you! Our plans include;<br/>
    Month-To-Month <br/>
    3-Month Contract <br/>
    6-Month Contract <br/>
    9-Month Contract <br/>
    1-Year Contract <br/>
    With a contract signing, we do require a payment for the full term up front before you can get access to the website.
    This helps reduce possible cancelation, and ensures that you have services with EZ-Rater Pro for the duration
    of that contract lenth.<br/>

  </p>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1 class="ez_home_header">EZ-Rater Pro</h1>

  <h2 class="ez_home_paragraph">
    The <strong>ULTIMATE</strong> EZ-Rating software suitable for all business sizes.<br/>
    Own your own business? Use our online tool to help get you setup with insurance in NO TIME!
  </h2>

  <%= link_to "Login Now", login_path, class: "btn btn-lg btn-primary" %> <%= link_to "Register Now", signup_path, class: 'btn btn-lg btn-success' %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Agents') %>

<%= will_paginate %>

<ul class="users" style="background-color: #FFF; padding: 25px;">
  <h1>Your Agents:</h1><br/>
  <p style="text-align: center; font-size: 20px;">Total Number of Agents: <%= @users.count %></p>
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.username, user %>
      <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, data: { "turbo-method": :delete,
                                              turbo_confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row" style="background-color: #C0C0C0; padding: 30px;">
<h1>Sign up</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :agency_name %>
      <%= f.text_field :agency_name, class: 'form-control' %>

      <%= f.label :access_code %>
      <%= f.text_field :access_code, class: 'form-control', collection: 123 %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %><br/>
        <%= @user.first_name %><br/>
        <%= @user.last_name %><br/>
        <%= @user.email %><br/>
        <%= @user.agency_name %>
      </h1>
    </section>
  </aside>
</div>